- type: job
  id: SecurityDeputy
  name: job-name-security-deputy
  description: job-description-security-deputy
  playTimeTracker: JobSecurityDeputy
  requirements:
  - !type:RoleTimeRequirement
    role: JobSecurityOfficer
    time: 5h
  startingGear: security-deputy
  icon: "JobIconDetective"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - 2-2-2
  - Security 2
  - Admin 1
  - Control 1
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: DetectiveGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: DetectivePDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltHolsterFilled
  storage:
    back:
    - Flash

- type: chameleonOutfit
  id: DetectiveChameleonOutfit
  job: Detective
  hasMindShield: true
  equipment:
    head: ClothingHeadHatFedoraBrown
    mask: ClothingMaskGasSecurity
    neck: ClothingNeckTieDet
    gloves: ClothingHandsGlovesForensic
